#define tree_sitter_notist_external_scanner_create tree_sitter_notist_code_external_scanner_create
#define tree_sitter_notist_external_scanner_destroy tree_sitter_notist_code_external_scanner_destroy
#define tree_sitter_notist_external_scanner_reset tree_sitter_notist_code_external_scanner_reset
#define tree_sitter_notist_external_scanner_serialize tree_sitter_notist_code_external_scanner_serialize
#define tree_sitter_notist_external_scanner_deserialize tree_sitter_notist_code_external_scanner_deserialize
#define tree_sitter_notist_external_scanner_scan tree_sitter_notist_code_external_scanner_scan
#include "../../src/scanner.c"
