import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
const destination = join(root, 'notist-code/queries');
mkdirSync(destination, { recursive: true });
for (const file of readdirSync(join(root, 'queries'))) {
  if (!file.endsWith('.scm')) continue;
  let query = readFileSync(join(root, 'queries', file), 'utf8');
  if (file === 'highlights.scm') {
    query += '\n(let_statement name: (identifier) @variable)\n(wasm_statement path: (string) @string.special)\n';
  }
  writeFileSync(join(destination, file), '; Generated by scripts/sync-queries.mjs.\n' + query);
}
